/'
Copyright (c) 2025 Ahmed R. Sadik, Honda Research Institute Europe GmbH

This source code is licensed under the MIT License found in the
LICENSE file in the root directory of this source tree. This dataset contains smelly code for research and refactoring purposes.
'/

@startwbs
<style>
/* Root level */
.wbs0 {
  BackgroundColor LightBlue
  FontColor Black
  FontSize 18
  FontStyle bold
}

/* First level (Categories) */
.wbs1 {
  BackgroundColor LightGreen
  FontColor Black
  FontSize 16
  FontStyle bold
}

/* Second level (Specific code smells) */
.wbs2 {
  BackgroundColor LightYellow
  FontColor Black
  FontSize 14
}
</style>

* Code Smells
** Bloaters
*** Long Method
*** Large Class
*** Primitive Obsession
*** Long Parameter List
*** Data Clumps
** Object-Orientation Abusers
*** Switch Statements
*** Temporary Field
*** Refused Bequest
*** Alternative Classes with Different Interfaces
** Change Preventers
*** Divergent Change
*** Shotgun Surgery
*** Parallel Inheritance Hierarchies
** Dispensables
*** Comments
*** Duplicate Code
*** Lazy Class
*** Data Class
*** Dead Code
*** Speculative Generality
** Couplers
*** Feature Envy
*** Inappropriate Intimacy
*** Message Chains
*** Middle Man
@endwbs
