/'
Copyright (c) 2025 Ahmed R. Sadik, Honda Research Institute Europe GmbH

This source code is licensed under the MIT License found in the
LICENSE file in the root directory of this source tree. This dataset contains smelly code for research and refactoring purposes.
'/

@startuml
|Customer|
start
:Place Order;
|Casher|
:Order Pizza;
|Chef|
:Bake Pizza;
|Customer|
:Complain to the Casher;
|Casher|
:Hurry Up Chef;
:Calm Down Customer;
|Chef|
:Cut and Box Pizza;
:Deliver Pizza;
stop
@enduml








