name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install Python dependencies (optional)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: .
          args: >
            -Dsonar.projectKey=claireeeeeeee_SmellyCodeDataset
            -Dsonar.organization=claireeeeeeee
            -Dsonar.sources=Python,Java,C++,JavaScript
            -Dsonar.inclusions=**/*.py,**/*.java,**/*.cpp,**/*.js
            -Dsonar.exclusions=**/__pycache__/**,**/*.md,**/tests/**,**/*.txt
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
